/* http://meyerweb.com/eric/tools/css/reset/ 
   v2.0 | 20110126
   License: none (public domain)
*/

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed, 
figure, figcaption, footer, header, hgroup, 
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure, 
footer, header, hgroup, menu, nav, section {
  display: block;
}
body {
  line-height: 1;
}
ol, ul {
  list-style: none;
}
blockquote, q {
  quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
  content: '';
  content: none;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}

.wrap{
  margin:0 auto;
  width:1000px;
  font-family:微軟正黑體;
}
.topmenu{
  background:#f6f6f6;
  margin-bottom:5px;
}
.topmenu ul{
  float:right;
}
.clearfix{
  clear:both;
}
.topmenu li{
  float:left;
  margin:5px;
}
.clearfix{
  clear:both;
}
.topmenu li a{
  display:block;
  text-decoration: none;
  font-size: 16px
}
.topmenu li a:hover{
  color:#00cc99;
}
.topmenu li img{
  margin-right:6px;
  float:left;
}
.clearfix{
  clear:both;
}
.topmenu li span{
  float:left;
}
.clearfix{
  clear:both;
}
.fb-icon{
  border-right:2px solid gray;
  padding-right:8px;
}
.logo{
  background-image:url(../img/images/logo.png);
  width:170px;
  height:36px;
  text-indent:101%;
  overflow:hidden;
  white-space:nowrap;
  float:left;
}
.clearfix{
  clear:both;
}
.menu{
  float:right;
}
.clearfix{
  clear:both;
}
.menu li{
  float:left;
}
.clearfix{
  clear:both;
}
.menu li a{
  display:block;
  width:70px;
  text-decoration:none;
  background:#fff;
  color:#00cc99;
  text-align:center;
  padding:10px;
}
.menu li a:hover{
  border-bottom: 2px solid #00cc99;
}
.header{
  margin-bottom:5px;
}
.clearfix{
  clear:both;
}
.course{
  margin-top:10px;
}
.course li{
  width:280px;
  height:300px;
  border:1px solid gray;
  box-shadow:5px 5px 5px gray;
  float:left;
  text-align:center;
  padding:10px;
  margin-right:15px;
  margin-left:15px;
}
.clearfix{
  clear:both;
}
.course li img{
  padding:10px;
}
.course li h3{
  font-weight:bold;
  font-size:18px;
  line-height:30px;
}
.course li p{
  font-size:14px;
  text-align:left;
  line-height:25px;
}
.course li h4{
  font-size:14px;
  text-align:left;
  line-height:25px;
}

.clearfix{
  clear:both;
}
h2{
  text-align:center;
  margin:50px;
  font-size:24px;
}
.compare{
  margin:0 auto;
}
.compare th{
  background-color:gray;
  width:200px;
  border-top:1px solid gray;
  border-bottom:1px solid gray;
  text-align:left;
  padding:10px;
  font-size:15px;
}
.compare td{
  width:200px;
  border-top:1px solid gray;
  border-bottom:1px solid gray;
  text-align:left;
  padding:10px;
  font-size:15px;
}
.compare span{
  color:#00cc99;
}
.clearfix{
  clear:both;
}
.form{
  background-image:url(../img/images/form-bg2.png);
  background-repeat: repeat-x;
  padding:10px;
  margin-top:30px;
  margin-bottom:10px;
}
.form h3{
  color:white;
  font-size:20px;
  text-align:center;
  padding-top:10px;
}
.form-left{
  float:left;
  margin-left:
}
.clearfix{
  clear:both;
}
textarea{
  margin:30px;
  width:450px;
}
.form-right{
  float:left;
  border-radius:5px
  color:white;
  font-weight:bold;
  width:450px;
  margin-top:40px;
  margin-left:10px;
}
.clearfix{
  clear:both;
}
.box1,.box2,.box3{
  width:400px;
  border-radius:3px;
  margin-top:10px;
  margin-bottom:10px;
}
.box4{
  float:right;
  margin-right:50px; 
  margin-top:20px;
  color:white;
  background-color:#00cc99;
  border:1px solid #00cc99;
  padding:5px;
  cursor: pointer;
}
.box4：hover{
  color:red;
}

.clearfix{
  clear:both;
}
.footer{
  padding:20px;
  margin-bottom:50px;
}
.footer-left{
  background-image:url(../img/images/footer-logo.png);
  width:170px;
  height:36px;
  text-indent:101%;
  overflow:hidden;
  white-space:nowrap;
  float:left;
}
.footer-right{
  float:right;
}
.footer-right p{
  float:left;
  color:black;
}

.footer span{
  color:pink;
}
